- name: restart consul
  service:
    name: consul
    state: restarted

- name: restart docker
  service:
    name: docker
    state: restarted

- name: restart swarm
  service:
    name: swarm
    state: restarted

