---

- name: Consul | Install unzip
  apt: pkg=unzip

- name: Consul | Download consul
  command: curl -LO https://dl.bintray.com/mitchellh/consul/{{consul_version}}_linux_amd64.zip
  args:
    chdir: /tmp
    creates: /usr/local/bin/consul

- name: Consul | Unzip consul
  command: unzip {{consul_version}}_linux_amd64.zip
  args:
    chdir: /tmp
    creates: /usr/local/bin/consul

- name: Consul | Move consul into /usr/local/bin
  command: mv /tmp/consul /usr/local/bin/consul
  args:
    creates: /usr/local/bin/consul
  notify:
    - restart consul

- name: Consul | Creates consul.d directory
  file: path=/etc/consul.d state=directory

- name: Consul | Install the consul upstart script
  template:
    src: consul.conf
    dest: /etc/init/consul.conf
  notify:
    - restart consul
