---

- name: Install unzip
  apt: pkg=unzip

- name: Download consul
  command: curl -LO https://dl.bintray.com/mitchellh/consul/{{consul_version}}_linux_amd64.zip
  args:
    chdir: /tmp
    creates: /usr/bin/consul

- name: Unzip consul
  command: unzip {{consul_version}}_linux_amd64.zip
  args:
    chdir: /tmp
    creates: /usr/bin/consul

- name: Move consul into /usr/bin
  command: mv /tmp/consul /usr/bin/consul
  args:
    creates: /usr/bin/consul
