---

galaxy_info:
  author: Chris Petersen
  description: Install and configure consul
  license: MIT
  min_ansible_version: 1.4
  platforms:
    - name: Ubuntu
      versions:
        - trusty
  categories:
    - cloud
dependencies: []
