---

- name: Registrator | Install registrator
  shell: GOPATH=/opt/gocode go get -u github.com/progrium/registrator
  args:
    creates: /opt/gocode/bin/registrator

- name: Registrator | Install the registrator upstart script
  template:
    src: registrator.conf
    dest: /etc/init/registrator.conf
  notify:
    - restart registrator
