---

- name: Docker | Add ubuntu keyserver
  apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: Docker | Add docker apt repo
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present

- name: Docker | Install docker
  apt: pkg=lxc-docker update_cache=true

- name: Docker | Install the docker upstart script
  template:
    src: docker.conf
    dest: /etc/init/docker.conf
  notify:
    - restart docker

# - name: Docker | Install the docker consul service
#   template:
#     src: docker.json
#     dest: /etc/consul.d/docker.json
#   notify:
#     - restart consul
