---

- name: Docker | Add ubuntu keyserver
  apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9

- name: Docker | Add docker apt repo
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present

- name: Docker | Install docker
  apt: pkg=lxc-docker

- name: Docker | Install the docker upstart script
  template:
    src: docker.conf
    dest: /etc/init/docker.conf
  register: docker_conf_result
  notify:
    - restart docker

- name: Docker | restart docker
  service: name=docker state=restarted
  when: docker_conf_result.changed

- name: Docker | Check running containers
  shell: docker -H {{ ansible_default_ipv4.address }}:4243 ps -a
  register: docker_contents

- name: Docker | Launch registrator
  shell: DOCKER_HOST={{ ansible_default_ipv4.address }}:4243 docker run -d --env=DOCKER_HOST=http://{{ ansible_default_ipv4.address }}:4243 --restart=always --name={{ ansible_hostname }}-registrator progrium/registrator consul://{{ ansible_default_ipv4.address }}:8500
  when: docker_contents.stdout.find('{{ ansible_hostname }}-registrator') == -1

- name: Docker | Launch logspout
  shell: DOCKER_HOST={{ ansible_default_ipv4.address }}:4243 docker run -d --env=DOCKER_HOST=http://{{ ansible_default_ipv4.address }}:4243 --restart=always --name={{ ansible_hostname }}-logspout progrium/logspout syslog://logs.papertrailapp.com:38814
  when: docker_contents.stdout.find('{{ ansible_hostname }}-logspout') == -1

- name: Docker | Add DOCKER_HOST to ENV
  lineinfile: dest=/etc/bash.bashrc regexp="^export DOCKER_HOST" line="export DOCKER_HOST=tcp://{{ ansible_default_ipv4.address }}:4243"
