---
- name: ensure platform servers are configured
  hosts: platform
  vars:
    consul_server: yes
  roles:
    - role: cpetersen.consul
    - role: cpetersen.swarm
    - role: cpetersen.haproxy
    - role: cpetersen.rsyslog
    - role: cpetersen.registrator

- name: ensure worker servers are configured
  hosts: worker
  vars:
    consul_server: no
  roles:
    - role: cpetersen.consul
    - role: cpetersen.swarm
    - role: cpetersen.rsyslog
    - role: cpetersen.registrator
