---
- name: ensure database servers are configured
  hosts: database
  user: ubuntu
  sudo: yes
  vars:
    database_name: "cilantro_production"
    database_user: "cilantro"
    database_password: "MzvHCY2uhEX9Ni"
    database_hostname: "db.nestedset.com"
    database_port: 5432
  roles:
    - role: ANXS.monit
      monit_notify_email: "christopher.petersen+monit@gmail.com"

    - role: ANXS.postgresql
      monit_protection: true
      postgresql_databases:
        - name: "{{database_name}}"
      postgresql_users:
        - name: "{{database_user}}"
          pass: "{{database_password}}"
          encrypted: no
      postgresql_user_privileges:
        - name: "{{database_user}}"
          db: "{{datbase_name}}"
          priv: "ALL"

    # - role: joshualund.ufw
    #   ufw_connection_rate_limits:
    #     - {port: 22, protocol: tcp}
    #   ufw_whitelisted_ports:
    #     - {port: 22, protocol: tcp}
    #     - {port: 5432, protocol: tcp}

- name: ensure swarm is configured
  hosts: swarm
  roles:
    - role: cpetersen.swarm
