---

- name: Golang | Install golang
  apt: pkg=golang

- name: Golang | Creates GOPATH directory
  file: path=/opt/gocode state=directory

- name: Golang | Add GOPATH to ENV
  lineinfile: dest=/etc/bash.bashrc regexp="^export GOPATH" line="export GOPATH=/opt/gocode"

- name: Golang | Add $GOPATH/bin to PATH
  lineinfile: dest=/etc/bash.bashrc regexp="^export PATH=\$PATH:\/opt\/gocode\/bin" line="export PATH=$PATH:/opt/gocode/bin"
